language: java
sudo: false
jdk:
- oraclejdk7
install: ./installViaTravis.sh
script: ./buildViaTravis.sh
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/dists/gradle-2.9-bin/
before_install:
- openssl aes-256-cbc -K $encrypted_5434d186515e_key -iv $encrypted_5434d186515e_iv
-in gradle.properties.enc -out gradle.properties -d
after_success:
- ./gradlew check
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
